### ISSUE TITLE
Elixir binding example

### ISSUE THREAD

**Issue by jadbox** [carlosgaldino/concha#1]
It would be great to see an example of Elixir using Concha!

**Comment by carlosgaldino** [comment]
Hello, I'm not familiar with Elixir but from what I've seen, you could simply use it [like any other Erlang dependency](http://elixir-lang.org/getting-started/erlang-libraries.html)?! Something like:

```
ring = :concha.build(nodes)
:concha.lookup(some_key, ring)
%% and so on...
```

I hope it helps. Thanks.
