### ISSUE TITLE
New to erlang...** exception error: undefined function concha:new/2

### ISSUE THREAD

**Issue by wandering007** [carlosgaldino/concha#2]
hi! I am a newbie to erlang. I cannot pass the given example.
The error shown as follows:

```
> Ring = concha:new(5, Nodes).
** exception error: undefined function concha:new/2
```

**Comment by carlosgaldino** [comment]
Hi, did you pull the library as a dependency for your project?

One example to do this would be by using rebar3 and hex: https://hex.pm/packages/concha
